### ISSUE TITLE
Botón de búsqueda 

### ISSUE THREAD

**Issue by Gisel23** [AndresAlzateHoyos/mercadoliebre#2]
Posicionar hacia la derecha el botón de búsqueda en el
Modo Mobile

**Comment by AndresAlzateHoyos** [comment]
En las imágenes se ve la lupa a la derecha del buscador, pero en ninguna ejercitación dice que debe ser así, además, en la ejercitación de la clase 17 hay una muestra de cómo debería verse el trabajo al final y tiene la lupa adentro.
